Comment model
mattegan111/fakebook pull request #5
Opened 2021-10-26 03:42 UTC by mattegan111

2021-10-27 06:53 UTC, nathanrobb requested changes
Suggest splitting the like out of the comment PUT.

Possibly something we want to do for the Post routes too.

2021-10-27 06:53 UTC, nathanrobb commented on server/models/Comment.js
> +	},
Should this ref the user? `ref: 'User',`

2021-10-27 06:53 UTC, nathanrobb commented on server/models/Comment.js
> +	},
Should this ref the posts `ref: 'Post',`?

2021-10-27 06:53 UTC, nathanrobb commented on server/models/User.js
>  	},
Should this be updated in #4?

2021-10-27 06:53 UTC, nathanrobb commented on server/routes/comments.js
> +// @route   GET api/comments
When would we use this endpoint? Listing all the users comments? I feel like we'd usually just want these retrieved when we get a post?

2021-10-27 06:53 UTC, nathanrobb commented on server/routes/comments.js
> +// @route   POST api/comments
Did you consider doing something like this as a route instead `api/posts/:postId/comments` and `PUT api/posts/:postId/comments/:commentId`

I guess it makes the delete endpoint possibly a little strange (if we didn't want to require a post id... 🤔 maybe not an issue).

2021-10-27 06:53 UTC, nathanrobb commented on server/routes/comments.js
> +// @route   PUT api/comments/:id
We can only edit a comment or like a comment, we cant do both in the same request.

We should add a like endpoint IMO. eg `PATCH api/comments/:id/like` or PUT or w/e

2021-10-27 06:53 UTC, nathanrobb commented on server/routes/comments.js
> +		const comment = await Comment.findById(req.params.id);
We could do a where on the db here? Not sure how to do it in mongoose

```js
		const comment = await Comment.findById(req.params.id).Where({ author = req.user.id});
```

2021-10-31 08:04 UTC, closed without merging

2021-10-31 09:29 UTC, nathanrobb commented
Hmm seems this auto closed, thought that the base branch would switch to `main`... my bad.

Looks like there an active discussion to implement what I thought would happen here. https://github.com/github/feedback/discussions/4477

2021-10-31 20:28 UTC, mattegan111 commented
Ok cool, I'm gonna try opening another PR for the comment-model branch. You might need to jump between PR's for context sorry!

2021-10-31 21:10 UTC, mattegan111 commented on server/models/User.js
>  	},
Yes, looks like I missed this and #4 is merged now, maybe I could've read comments across all branches before merging. I think it'd be best to open another branch for this later.

2021-10-31 21:11 UTC, mattegan111 commented on server/models/User.js
>  	},
Same with `friends`, `receivedfriendrequests` and `sentfriendrequests`

2021-10-31 21:26 UTC, mattegan111 commented on server/routes/comments.js
> +// @route   GET api/comments
Could be useful for a "User's Recent Activity" component. But is 'could be useful' a good enough reason to merge into main?

2021-10-31 22:00 UTC, mattegan111 commented on server/routes/comments.js
> +// @route   POST api/comments
Your suggestion seems to better follow RESTful architecture, one potential advantage is having the post id accessible through the params. Let's use it.

Delete endpoint might be ok.

2021-10-31 23:32 UTC, mattegan111 commented on server/routes/comments.js
> +// @route   POST api/comments
Your suggestion is a proper RESTful architecture - I want to implement it but I realised I'd probably have to completely change the file structure for routing. It'd be nice to come back to it later if you think the current solution is good enough?

I did notice we're sanitising what should be a `req.body` property so I'll change that.

2021-11-01 02:20 UTC, mattegan111 commented on server/routes/comments.js
> +		const comment = await Comment.findById(req.params.id);
Ok cool. What's the advantage? Fewer lines of code? More efficient db requests?